### ISSUE TITLE
Without webhook? 

### ISSUE THREAD

**Issue by Ismoh** [nhevia/discord-styled-releases#5]
Is it possible to login to your discord account and send a message to a already joined discord server, because you arent the server admin and not able to provide the webhook url?

**Comment by nhevia** [comment]
No. You can only use it knowing the `TOKEN`, else anyone could spam messages.

If you're not the admin, you need the [`MANAGE_WEBOOKS`](https://discord.com/developers/docs/resources/webhook#create-webhook) permission to get the full URL (it can be given from the channel's permissions UI)
